<?php
$item_sets = $this->api()->search("item_sets")->getContent();
$escape = $this->plugin('escapeHtml');
?>
<?= $this->pageTitle("Generate museum"); ?>

<style>
/* Fix weird form style error */
.query-text {
	margin: auto!important;
}
</style>

<?php if($query == null): /* Stage 1 */ ?>
<form action="generate" method="GET">
	<?= $this->partial("common/advanced-search", ["query" => $query, "resourceType" => "item"]); ?>
	<input type="submit" value="Continue">
</form>

<?php else: /* Stage 2 */ ?>

<form action="view" method="GET">
    <table class="table" style="width:100%">
        <div style="text-align:right">
            <input type="checkbox" onClick="toggle(this)" checked />Select All<br/>
        </div>
        <tr>
            <th style="width:25%">Title</th>
            <th style="text-align:center">Preview</th>
        </tr>
    <?php foreach($items as $item) : ?>
        <?php $itemID = $item->id(); ?>
        <tr>
            <td style="width:25%">
                <?php echo $item->title(); ?>
            </td>
            <td style="text-align:center">
                <label for="<?=$itemID?>"><?=$this->thumbnail($item,'medium')?></label>
            </td>
            <td style="text-align:right">
                <input type="checkbox" id = "<?=$itemID?>" name="items[]" value="<?= $itemID ?>" checked>
            </td>
        </tr>
    <?php endforeach; ?>
    </table>
    <input type="submit" value="Generate">
</form>

<?php endif; ?>

<!-- script for selecting all checkboxes -->
<script language="JavaScript">
    function toggle(source) {
        checkboxes = document.getElementsByName('items[]');
        for(var i=0, n=checkboxes.length; i<n; i++) {
            checkboxes[i].checked = source.checked;
        }
    }
</script>
